site_name: Reign Wiki
site_description: Официальная документация мода Reign
site_url: https://idronov-mods.github.io/reign-wiki/

theme:
  name: material
  language: ru
  palette:
    - scheme: slate
      primary: black
      accent: yellow

nav:
  - Главная: index.md
  - Системы:
      - Дома: systems/houses.md
  - Механики:
