site_name: Reign Wiki
site_description: Официальная документация мода Reign
site_url: https://idronov-mods.github.io/reign-wiki/

theme:
  name: material
  language: ru
  palette:
    - scheme: slate

nav:
  - Главная: index.md
  - Системы:
      - Дома: systems/houses.md
  - Механики:
      - Экономика: systems/houses.md
      - Тюрьмы: systems/houses.md
